import type {
  Family,
  ItemDefinition,
  ItemInstance,
  ItemLevel,
  OpponentDefinition,
} from "./types";

export const FAMILY_META: Record<
  Family,
  { name: string; icon: string; color: string; shortBonus: string }
> = {
  fire: {
    name: "Feuer",
    icon: "🔥",
    color: "#ff7a3d",
    shortBonus: "22 % mehr Direktschaden",
  },
  poison: {
    name: "Gift",
    icon: "☠",
    color: "#86d85d",
    shortBonus: "+1 Gift und 5 % schneller",
  },
  guard: {
    name: "Schutz",
    icon: "◆",
    color: "#6ccff6",
    shortBonus: "12 Startschild und 15 % stärker",
  },
};

export const ITEMS: readonly ItemDefinition[] = [
  {
    id: "chili",
    name: "Chilischote",
    family: "fire",
    icon: "🌶️",
    cost: 3,
    cooldown: [3.2, 3, 2.7],
    values: [4, 9, 18],
    effect: "damage",
    descriptions: [
      "Schleudert 4 Feuerschaden.",
      "Schleudert 9 Feuerschaden.",
      "18 Schaden und hinterlässt Brand.",
    ],
    levelThreeBonus: "burn",
  },
  {
    id: "dragon-tooth",
    name: "Drachenzahn",
    family: "fire",
    icon: "🦷",
    cost: 4,
    cooldown: [4.5, 4.15, 3.8],
    values: [7, 15, 29],
    effect: "damage",
    descriptions: [
      "Treffer; jede Aktivierung macht ihn 18 % stärker.",
      "Starker Treffer; wächst im Kampf weiter.",
      "Gewaltiger Treffer; wächst im Kampf weiter.",
    ],
    scalesWithFamily: "fire",
    trigger: { type: "ramp", growthPerActivation: 0.18 },
  },
  {
    id: "ember-core",
    name: "Glutkern",
    family: "fire",
    icon: "🔸",
    cost: 3,
    cooldown: [4, 3.7, 3.35],
    values: [3, 7, 14],
    effect: "damage",
    descriptions: [
      "Schaden; beschleunigt Feuer-Nachbarn.",
      "Mehr Schaden und Nachbar-Tempo.",
      "Entfacht sehr schnelle Feuer-Nachbarn.",
    ],
    passive: {
      type: "hasteAdjacent",
      family: "fire",
      values: [0.18, 0.28, 0.38],
    },
  },
  {
    id: "cinder-berry",
    name: "Rußbeere",
    family: "fire",
    icon: "🫐",
    cost: 3,
    cooldown: [3.6, 3.3, 3],
    values: [3, 7, 13],
    secondaryValues: [4, 8, 14],
    effect: "conditionalDamage",
    descriptions: [
      "Trifft Vergiftete 4 Punkte härter.",
      "Trifft Vergiftete 8 Punkte härter.",
      "Trifft Vergiftete 14 Punkte härter.",
    ],
  },
  {
    id: "slime-shroom",
    name: "Schleimpilz",
    family: "poison",
    icon: "🍄",
    cost: 3,
    cooldown: [3.6, 3.3, 3],
    values: [3, 6, 10],
    effect: "poison",
    descriptions: [
      "Legt 3 Gift auf. 10 Gift lösen Toxinschock aus.",
      "Legt 6 Gift auf. 10 Gift lösen Toxinschock aus.",
      "Legt 10 Gift auf und löst sofort Toxinschock aus.",
    ],
  },
  {
    id: "nightwing",
    name: "Nachtflügel",
    family: "poison",
    icon: "🦇",
    cost: 4,
    cooldown: [4.1, 3.8, 3.4],
    values: [2, 5, 10],
    effect: "damage",
    descriptions: [
      "Kleiner Treffer; beschleunigt Nachbarn.",
      "Treffer und starkes Nachbar-Tempo.",
      "Treffer und extremes Nachbar-Tempo.",
    ],
    passive: {
      type: "hasteAdjacent",
      values: [0.16, 0.25, 0.35],
    },
  },
  {
    id: "witch-eye",
    name: "Hexenauge",
    family: "poison",
    icon: "👁️",
    cost: 3,
    cooldown: [3.4, 3.1, 2.8],
    values: [2, 5, 10],
    secondaryValues: [5, 10, 18],
    effect: "conditionalDamage",
    descriptions: [
      "Verursacht +5 Schaden gegen Vergiftete.",
      "Verursacht +10 gegen Vergiftete.",
      "Verursacht +18 gegen Vergiftete.",
    ],
  },
  {
    id: "venom-bulb",
    name: "Vipernknolle",
    family: "poison",
    icon: "🫛",
    cost: 4,
    cooldown: [4.3, 4, 3.6],
    values: [2, 5, 8],
    secondaryValues: [2, 4, 7],
    effect: "poisonDamage",
    descriptions: [
      "Schaden, Gift und Tempo für Giftitems.",
      "Mehr Schaden, Gift und Gift-Tempo.",
      "Starkes Gift und maximales Gift-Tempo.",
    ],
    passive: {
      type: "hasteFamily",
      family: "poison",
      values: [0.06, 0.11, 0.17],
    },
  },
  {
    id: "egg-shell",
    name: "Eierschale",
    family: "guard",
    icon: "🥚",
    cost: 3,
    cooldown: [3.8, 3.5, 3.15],
    values: [6, 13, 24],
    effect: "shield",
    descriptions: [
      "Erzeugt 6 Schild.",
      "Erzeugt 13 Schild.",
      "24 Schild und entfernt Gift.",
    ],
    levelThreeBonus: "cleansePoison",
  },
  {
    id: "healing-tuber",
    name: "Heilknolle",
    family: "guard",
    icon: "🥔",
    cost: 3,
    cooldown: [4.2, 3.9, 3.5],
    values: [6, 13, 23],
    effect: "heal",
    descriptions: [
      "Heilt einmal unter 50 % Leben.",
      "Heilt einmal unter 50 % Leben.",
      "Frühe Notfallheilung; Überheilung wird Schild.",
    ],
    levelThreeBonus: "overhealShield",
    trigger: { type: "emergency", threshold: 0.5, multiplier: 1.5 },
  },
  {
    id: "gold-spoon",
    name: "Goldlöffel",
    family: "guard",
    icon: "🥄",
    cost: 4,
    cooldown: [4.6, 4.25, 3.9],
    values: [4, 9, 16],
    secondaryValues: [4, 9, 16],
    effect: "hybrid",
    descriptions: [
      "Heilt, schützt und stärkt Schutz-Nachbarn.",
      "Starke Heilung und Nachbar-Verstärkung.",
      "Mächtige doppelte Schutzwirkung.",
    ],
    passive: {
      type: "powerAdjacent",
      family: "guard",
      values: [0.16, 0.24, 0.34],
    },
  },
  {
    id: "moon-salt",
    name: "Mondsalz",
    family: "guard",
    icon: "🧂",
    cost: 3,
    cooldown: [4, 3.65, 3.3],
    values: [4, 9, 16],
    secondaryValues: [3, 7, 13],
    effect: "shieldDamage",
    descriptions: [
      "Kontert abgefangene oder ungeschützte Treffer.",
      "Stärkerer Trefferkonter mit Schild und Splitter.",
      "Massiver Trefferkonter mit Schild und Splitter.",
    ],
    trigger: { type: "onGuardedHit" },
  },
] as const;

export const ITEM_BY_ID = Object.fromEntries(
  ITEMS.map((item) => [item.id, item]),
) as Record<string, ItemDefinition>;

function enemyItem(
  opponent: string,
  slot: number,
  itemId: string,
  level: ItemLevel = 1,
): ItemInstance {
  return { uid: `${opponent}-${slot}-${itemId}`, itemId, level };
}

export const CAMPAIGN_OPPONENTS: readonly OpponentDefinition[] = [
  {
    id: "zischbert",
    name: "Zischbert",
    title: "Der Anheizer",
    icon: "🔥",
    quote: "Das wird gleich angenehm ungemütlich.",
    threat: "Klare Feuerangriffe, aber keinerlei Schutz",
    rank: "regular",
    baseHp: 65,
    board: [
      enemyItem("zischbert", 0, "chili", 1),
      enemyItem("zischbert", 1, "cinder-berry", 1),
      null,
      null,
      null,
    ],
    boardVariants: [
      [
        enemyItem("zischbert-a", 0, "chili", 1),
        enemyItem("zischbert-a", 1, "ember-core", 1),
        null,
        null,
        null,
      ],
      [
        enemyItem("zischbert-b", 0, "dragon-tooth", 1),
        enemyItem("zischbert-b", 1, "nightwing", 1),
        null,
        null,
        null,
      ],
    ],
  },
  {
    id: "moor-martha",
    name: "Moor-Martha",
    title: "Die Geduldige",
    icon: "🍄",
    quote: "Nur nicht so tief einatmen, Schätzchen.",
    threat: "Gift wächst langsam, aber zuverlässig",
    rank: "regular",
    baseHp: 86,
    board: [
      enemyItem("martha", 0, "slime-shroom", 1),
      enemyItem("martha", 1, "nightwing", 2),
      null,
      null,
      null,
    ],
    boardVariants: [
      [
        enemyItem("martha-a", 0, "slime-shroom", 1),
        enemyItem("martha-a", 1, "witch-eye", 2),
        null,
        null,
        null,
      ],
      [
        enemyItem("martha-b", 0, "venom-bulb", 2),
        enemyItem("martha-b", 1, "nightwing", 1),
        null,
        null,
        null,
      ],
    ],
  },
  {
    id: "schild-siggi",
    name: "Schild-Siggi",
    title: "Der Unverrückbare",
    icon: "◆",
    quote: "Klopf ruhig. Ich hör fast nichts.",
    threat: "Viel Schild, aber nur schwacher Gegenschaden",
    rank: "regular",
    baseHp: 86,
    board: [
      enemyItem("siggi", 0, "egg-shell", 1),
      enemyItem("siggi", 1, "gold-spoon", 1),
      enemyItem("siggi", 2, "moon-salt", 1),
      enemyItem("siggi", 3, "chili", 1),
      null,
    ],
    boardVariants: [
      [
        enemyItem("siggi-a", 0, "egg-shell", 1),
        enemyItem("siggi-a", 1, "chili", 1),
        enemyItem("siggi-a", 2, "moon-salt", 1),
        null,
        null,
      ],
      [
        enemyItem("siggi-b", 0, "gold-spoon", 1),
        enemyItem("siggi-b", 1, "moon-salt", 1),
        enemyItem("siggi-b", 2, "chili", 1),
        null,
        null,
      ],
    ],
  },
  {
    id: "knister-klara",
    name: "Knister-Klara",
    title: "Die Kombiniererin",
    icon: "⚡",
    quote: "Erst grün, dann rot – und dann wird’s laut.",
    threat: "Rußbeeren treffen vergiftete Kessel härter",
    rank: "regular",
    baseHp: 106,
    board: [
      enemyItem("klara", 0, "slime-shroom", 1),
      enemyItem("klara", 1, "nightwing", 1),
      enemyItem("klara", 2, "cinder-berry", 2),
      enemyItem("klara", 3, "chili", 2),
      null,
    ],
    boardVariants: [
      [
        enemyItem("klara-a", 0, "venom-bulb", 1),
        enemyItem("klara-a", 1, "cinder-berry", 2),
        enemyItem("klara-a", 2, "chili", 2),
        enemyItem("klara-a", 3, "nightwing", 1),
        null,
      ],
      [
        enemyItem("klara-b", 0, "slime-shroom", 1),
        enemyItem("klara-b", 1, "witch-eye", 1),
        enemyItem("klara-b", 2, "ember-core", 2),
        enemyItem("klara-b", 3, "cinder-berry", 2),
        null,
      ],
    ],
  },
  {
    id: "tox-toni",
    name: "Tox-Toni",
    title: "Der Moorflüsterer",
    icon: "☠",
    quote: "Ein Tropfen ist Zufall. Zehn sind ein Plan.",
    threat: "Aktive Gift-Synergie und beschleunigte Stapel",
    rank: "regular",
    baseHp: 112,
    board: [
      enemyItem("toni", 0, "slime-shroom", 2),
      enemyItem("toni", 1, "nightwing", 1),
      enemyItem("toni", 2, "witch-eye", 2),
      enemyItem("toni", 3, "venom-bulb", 2),
      null,
    ],
    boardVariants: [
      [
        enemyItem("toni-a", 0, "venom-bulb", 2),
        enemyItem("toni-a", 1, "nightwing", 2),
        enemyItem("toni-a", 2, "slime-shroom", 1),
        enemyItem("toni-a", 3, "witch-eye", 2),
        null,
      ],
      [
        enemyItem("toni-b", 0, "nightwing", 1),
        enemyItem("toni-b", 1, "slime-shroom", 2),
        enemyItem("toni-b", 2, "cinder-berry", 2),
        enemyItem("toni-b", 3, "venom-bulb", 2),
        null,
      ],
    ],
  },
  {
    id: "broesel-berta",
    name: "Brösel-Berta",
    title: "Die Eisenbäckerin",
    icon: "🥚",
    quote: "Unter jeder guten Kruste steckt ein kleines Feuer.",
    threat: "Schutz-Synergie hält starke Feuerangriffe am Leben",
    rank: "regular",
    baseHp: 112,
    board: [
      enemyItem("berta", 0, "egg-shell", 2),
      enemyItem("berta", 1, "dragon-tooth", 2),
      enemyItem("berta", 2, "chili", 2),
      enemyItem("berta", 3, "moon-salt", 1),
      null,
    ],
    boardVariants: [
      [
        enemyItem("berta-a", 0, "moon-salt", 1),
        enemyItem("berta-a", 1, "gold-spoon", 1),
        enemyItem("berta-a", 2, "dragon-tooth", 2),
        enemyItem("berta-a", 3, "egg-shell", 1),
        null,
      ],
      [
        enemyItem("berta-b", 0, "moon-salt", 2),
        enemyItem("berta-b", 1, "egg-shell", 1),
        enemyItem("berta-b", 2, "chili", 2),
        enemyItem("berta-b", 3, "ember-core", 2),
        null,
      ],
    ],
  },
  {
    id: "meisterin-mirea",
    name: "Meisterin Mirea",
    title: "Elite des Flammenbunds",
    icon: "✦",
    quote: "Ich brauche keinen großen Kessel. Nur den richtigen.",
    threat: "Explosive Feuer-Synergie mit perfekt gesetztem Glutkern",
    rank: "elite",
    rewardBonus: 2,
    baseHp: 126,
    board: [
      enemyItem("mirea", 0, "dragon-tooth", 1),
      enemyItem("mirea", 1, "chili", 2),
      enemyItem("mirea", 2, "ember-core", 2),
      enemyItem("mirea", 3, "cinder-berry", 1),
      enemyItem("mirea", 4, "nightwing", 1),
    ],
    boardVariants: [
      [
        enemyItem("mirea-a", 0, "ember-core", 2),
        enemyItem("mirea-a", 1, "dragon-tooth", 2),
        enemyItem("mirea-a", 2, "chili", 1),
        enemyItem("mirea-a", 3, "nightwing", 1),
        enemyItem("mirea-a", 4, "cinder-berry", 1),
      ],
      [
        enemyItem("mirea-b", 0, "nightwing", 1),
        enemyItem("mirea-b", 1, "chili", 2),
        enemyItem("mirea-b", 2, "ember-core", 2),
        enemyItem("mirea-b", 3, "dragon-tooth", 1),
        enemyItem("mirea-b", 4, "witch-eye", 1),
      ],
    ],
  },
  {
    id: "grosskessel",
    name: "Der Großkessel",
    title: "Meister des Kesselturniers",
    icon: "♛",
    quote: "Kleine Zutaten. Große Hoffnungen.",
    threat: "Kesselzorn: Unter 50 % Leben werden alle Wirkungen 25 % stärker",
    rank: "boss",
    bossRule: "rageAtHalf",
    baseHp: 142,
    board: [
      enemyItem("boss", 0, "dragon-tooth", 2),
      enemyItem("boss", 1, "chili", 1),
      enemyItem("boss", 2, "slime-shroom", 2),
      enemyItem("boss", 3, "gold-spoon", 2),
      enemyItem("boss", 4, "egg-shell", 1),
    ],
    boardVariants: [
      [
        enemyItem("boss-a", 0, "ember-core", 2),
        enemyItem("boss-a", 1, "dragon-tooth", 2),
        enemyItem("boss-a", 2, "venom-bulb", 2),
        enemyItem("boss-a", 3, "healing-tuber", 2),
        enemyItem("boss-a", 4, "moon-salt", 1),
      ],
      [
        enemyItem("boss-b", 0, "nightwing", 2),
        enemyItem("boss-b", 1, "slime-shroom", 2),
        enemyItem("boss-b", 2, "cinder-berry", 2),
        enemyItem("boss-b", 3, "gold-spoon", 2),
        enemyItem("boss-b", 4, "egg-shell", 1),
      ],
    ],
  },
] as const;
