import type {
  Family,
  ItemDefinition,
  ItemInstance,
  ItemLevel,
  OpponentDefinition,
} from "./types";

export const FAMILY_META: Record<
  Family,
  { name: string; icon: string; color: string; shortBonus: string }
> = {
  fire: {
    name: "Feuer",
    icon: "🔥",
    color: "#ff7a3d",
    shortBonus: "+22 % Direktschaden",
  },
  poison: {
    name: "Gift",
    icon: "☠",
    color: "#86d85d",
    shortBonus: "+1 Giftstapel",
  },
  guard: {
    name: "Schutz",
    icon: "◆",
    color: "#6ccff6",
    shortBonus: "Startschild & +15 %",
  },
};

export const ITEMS: readonly ItemDefinition[] = [
  {
    id: "chili",
    name: "Chilischote",
    family: "fire",
    icon: "🌶️",
    cost: 3,
    cooldown: [3.2, 3, 2.7],
    values: [4, 9, 18],
    effect: "damage",
    descriptions: [
      "Schleudert 4 Feuerschaden.",
      "Schleudert 9 Feuerschaden.",
      "18 Schaden und hinterlässt Brand.",
    ],
    levelThreeBonus: "burn",
  },
  {
    id: "dragon-tooth",
    name: "Drachenzahn",
    family: "fire",
    icon: "🦷",
    cost: 4,
    cooldown: [4.5, 4.15, 3.8],
    values: [7, 15, 29],
    effect: "damage",
    descriptions: [
      "Schwerer Treffer; wächst mit Feuer.",
      "Starker Treffer; wächst mit Feuer.",
      "Gewaltiger Treffer; wächst mit Feuer.",
    ],
    scalesWithFamily: "fire",
  },
  {
    id: "ember-core",
    name: "Glutkern",
    family: "fire",
    icon: "🔸",
    cost: 3,
    cooldown: [4, 3.7, 3.35],
    values: [3, 7, 14],
    effect: "damage",
    descriptions: [
      "Schaden; beschleunigt Feuer-Nachbarn.",
      "Mehr Schaden und Nachbar-Tempo.",
      "Entfacht sehr schnelle Feuer-Nachbarn.",
    ],
    passive: {
      type: "hasteAdjacent",
      family: "fire",
      values: [0.12, 0.2, 0.3],
    },
  },
  {
    id: "cinder-berry",
    name: "Rußbeere",
    family: "fire",
    icon: "🫐",
    cost: 3,
    cooldown: [3.6, 3.3, 3],
    values: [3, 7, 13],
    secondaryValues: [4, 8, 14],
    effect: "conditionalDamage",
    descriptions: [
      "Trifft Vergiftete 4 Punkte härter.",
      "Trifft Vergiftete 8 Punkte härter.",
      "Trifft Vergiftete 14 Punkte härter.",
    ],
  },
  {
    id: "slime-shroom",
    name: "Schleimpilz",
    family: "poison",
    icon: "🍄",
    cost: 3,
    cooldown: [3.6, 3.3, 3],
    values: [3, 6, 10],
    effect: "poison",
    descriptions: [
      "Legt 3 Giftstapel auf.",
      "Legt 6 Giftstapel auf.",
      "Legt 10 Giftstapel auf.",
    ],
  },
  {
    id: "nightwing",
    name: "Nachtflügel",
    family: "poison",
    icon: "🦇",
    cost: 4,
    cooldown: [4.1, 3.8, 3.4],
    values: [2, 5, 10],
    effect: "damage",
    descriptions: [
      "Kleiner Treffer; beschleunigt Nachbarn.",
      "Treffer und starkes Nachbar-Tempo.",
      "Treffer und extremes Nachbar-Tempo.",
    ],
    passive: {
      type: "hasteAdjacent",
      values: [0.1, 0.17, 0.25],
    },
  },
  {
    id: "witch-eye",
    name: "Hexenauge",
    family: "poison",
    icon: "👁️",
    cost: 3,
    cooldown: [3.4, 3.1, 2.8],
    values: [2, 5, 10],
    secondaryValues: [5, 10, 18],
    effect: "conditionalDamage",
    descriptions: [
      "Verursacht +5 Schaden gegen Vergiftete.",
      "Verursacht +10 gegen Vergiftete.",
      "Verursacht +18 gegen Vergiftete.",
    ],
  },
  {
    id: "venom-bulb",
    name: "Vipernknolle",
    family: "poison",
    icon: "🫛",
    cost: 4,
    cooldown: [4.3, 4, 3.6],
    values: [2, 5, 8],
    secondaryValues: [2, 4, 7],
    effect: "poisonDamage",
    descriptions: [
      "Schaden, Gift und Tempo für Giftitems.",
      "Mehr Schaden, Gift und Gift-Tempo.",
      "Starkes Gift und maximales Gift-Tempo.",
    ],
    passive: {
      type: "hasteFamily",
      family: "poison",
      values: [0.06, 0.11, 0.17],
    },
  },
  {
    id: "egg-shell",
    name: "Eierschale",
    family: "guard",
    icon: "🥚",
    cost: 3,
    cooldown: [3.8, 3.5, 3.15],
    values: [6, 13, 24],
    effect: "shield",
    descriptions: [
      "Erzeugt 6 Schild.",
      "Erzeugt 13 Schild.",
      "24 Schild und entfernt Gift.",
    ],
    levelThreeBonus: "cleansePoison",
  },
  {
    id: "healing-tuber",
    name: "Heilknolle",
    family: "guard",
    icon: "🥔",
    cost: 3,
    cooldown: [4.2, 3.9, 3.5],
    values: [6, 13, 23],
    effect: "heal",
    descriptions: [
      "Heilt 6 Leben.",
      "Heilt 13 Leben.",
      "23 Heilung; Überheilung wird Schild.",
    ],
    levelThreeBonus: "overhealShield",
  },
  {
    id: "gold-spoon",
    name: "Goldlöffel",
    family: "guard",
    icon: "🥄",
    cost: 4,
    cooldown: [4.6, 4.25, 3.9],
    values: [4, 9, 16],
    secondaryValues: [4, 9, 16],
    effect: "hybrid",
    descriptions: [
      "Heilt, schützt und stärkt Schutz-Nachbarn.",
      "Starke Heilung und Nachbar-Verstärkung.",
      "Mächtige doppelte Schutzwirkung.",
    ],
    passive: {
      type: "powerAdjacent",
      family: "guard",
      values: [0.1, 0.16, 0.24],
    },
  },
  {
    id: "moon-salt",
    name: "Mondsalz",
    family: "guard",
    icon: "🧂",
    cost: 3,
    cooldown: [4, 3.65, 3.3],
    values: [5, 11, 20],
    secondaryValues: [2, 5, 10],
    effect: "shieldDamage",
    descriptions: [
      "Erzeugt Schild und schleudert Splitter.",
      "Mehr Schild und Splitterschaden.",
      "Massiver Schild und Gegentreffer.",
    ],
  },
] as const;

export const ITEM_BY_ID = Object.fromEntries(
  ITEMS.map((item) => [item.id, item]),
) as Record<string, ItemDefinition>;

function enemyItem(
  opponent: string,
  slot: number,
  itemId: string,
  level: ItemLevel = 1,
): ItemInstance {
  return { uid: `${opponent}-${slot}-${itemId}`, itemId, level };
}

export const CORE_OPPONENTS: readonly OpponentDefinition[] = [
  {
    id: "zischbert",
    name: "Zischbert",
    title: "Der Anheizer",
    icon: "🔥",
    quote: "Das wird gleich angenehm ungemütlich.",
    threat: "Schneller Direktschaden, kaum Schutz",
    baseHp: 92,
    board: [
      enemyItem("zischbert", 0, "chili", 1),
      enemyItem("zischbert", 1, "ember-core", 1),
      enemyItem("zischbert", 2, "dragon-tooth", 1),
      null,
      null,
    ],
  },
  {
    id: "moor-martha",
    name: "Moor-Martha",
    title: "Die Geduldige",
    icon: "🍄",
    quote: "Nur nicht so tief einatmen, Schätzchen.",
    threat: "Gift wächst mit jeder Sekunde",
    baseHp: 100,
    board: [
      enemyItem("martha", 0, "slime-shroom", 1),
      enemyItem("martha", 1, "nightwing", 1),
      enemyItem("martha", 2, "witch-eye", 1),
      null,
      null,
    ],
  },
  {
    id: "schild-siggi",
    name: "Schild-Siggi",
    title: "Der Unverrückbare",
    icon: "◆",
    quote: "Klopf ruhig. Ich hör fast nichts.",
    threat: "Heilung und Schild, niedriger Angriff",
    baseHp: 108,
    board: [
      enemyItem("siggi", 0, "egg-shell", 1),
      enemyItem("siggi", 1, "gold-spoon", 1),
      enemyItem("siggi", 2, "moon-salt", 1),
      null,
      null,
    ],
  },
] as const;
